package com.maven8919.lineupgenerator.domain;

public enum Team {
    HAWKS,NETS,CELTICS,
    HORNETS, BULLS, CAVS,
    MAVS, NUGGETS, PISTONS,
    WARRIORS, ROCKETS, PACERS,
    CLIPPERS, LAKERS, GRIZZLIES,
    HEAT, WOLVES, BUCKS,
    PELICANS, KNICKS, THUNDER,
    MAGIC, _76ERS, SUNS,
    BLAZERS, KINGS, SPURS,
    RAPTORS, JAZZ, WIZARDS;
}
